### ISSUE TITLE
syntax errors and permission denied errors in docker-compose deployment

### ISSUE THREAD

**Issue by fightingtexasaggie** [linagora/linshare-docker#1]
Hello and first let me thank you for your work in developing linshare. The open source community really needed this!

I'm trying to host this and have noticed some errors preventing it from starting up. In particular:

linshare_frontend | httpd: Could not open configuration file /usr/local/apache2/conf/httpd.conf: Permission denied
linshare_backend | cp: failed to access ‘/etc/linshare/log4j.properties’: Permission denied
linshare_mongodb | chown: cannot read directory '/data/db': Permission denied
linshare_smtp | warn: /etc/smtpd/smtpd.conf: Permission denied
linshare_ui-admin | AH00526: Syntax error on line 15 of /usr/local/apache2/conf/extra/linshare-ui-admin.conf:
linshare_ui-admin | SSLCertificateFile: file '/usr/local/apache2/conf/server.crt' does not exist or is empty
linshare_ui-user | AH00526: Syntax error on line 17 of /usr/local/apache2/conf/extra/linshare-ui-user.conf:
linshare_ui-user | SSLCertificateFile: file '/usr/local/apache2/conf/server.crt' does not exist or is empty
linshare_database | mkdir: cannot create directory ‘/var/lib/postgresql/data/pgdata’: Permission denied

For full log: https://pastebin.com/xNB3AkwK

Thank you,
Michael

**Comment by fmartin-linagora** [comment]
Hi,
Thank you for you comment, sorry for the delay I was in holidays. It seems you have a permissions issue on the folder name data. Every container which contains data to persist will create a personnal folder into the folder data. 

```
data                                                                                                                                                                                                                
├── linshare_data                                                                                                                                                                                                   
│   └── lib                                                                                                                                                                                                         
├── mongodb_data                                                                                                                                                                                                    
│   └── db                                                                                                                                                                                                          
├── postgres_data                                                                                                                                                                                                   
│   └── lib                                                                                                                                                                                                         
└── smtp_data                                                                                                                                                                                                       
    └── spool                                                                                                                                                                                                       
```

**Comment by fightingtexasaggie** [comment]
Thank you! I'll give this a try.
