### ISSUE TITLE
Prompting to install admin ui even after it is installed

### ISSUE THREAD

**Issue by arjungprs** [linagora/linshare-docker#10]
Hi, 
I am getting this error when I access http://myip/linshare : 

> Welcome to LinShare Core. LinShare is up and running ! please Install linshare-ui-admin component to configure LinShare.

I am able to see the admin ui in here :  http://myip

I followed the exact steps from here : https://github.com/linagora/linshare/blob/master/documentation/EN/installation/linshare-install-centos.md
Kindly advise what needs to be done.
Thanks
ajp

**Comment by fmartin-linagora** [comment]
I'm closing this issue because it is already opened [here](https://github.com/linagora/linshare/issues/98).
