### ISSUE TITLE
"page not found" from linshare-docker

### ISSUE THREAD

**Issue by arjungprs** [linagora/linshare-docker#11]
Hi,
I am setting up the linshare -docker in centos 7. I am getting "page not found" when I hit the http://myvpsipaddress. I am using VPS server. Could you please help me to start debugging this please. where should I look for the logs please.

[root@centos-01 linshare-docker]# docker-compose up -d
Starting linshare_mongodb ... done
Starting linshare_ldap ... done
Starting linshare_init ... done
Starting linshare_thumbnail-server ... done
Starting linshare_docker-socket ... done
Starting linshare_database ... done
Starting linshare_smtp ... done
Starting linshare_home ... done
Starting linshare_reverse-proxy ... done
Starting linshare_clamav ... done
Starting linshare_backend ... done
Starting linshare_ui-user ... done
Starting linshare_ui-admin ... done

I am using the instructions from https://github.com/linagora/linshare-docker
Thanks,
Ajp

**Comment by fmartin-linagora** [comment]
Hi,
You must not try to access the service using your IP, you must use the virtual names defined in the README, cf:
`127.0.0.1 admin.linshare.local user.linshare.local linshare.local traefik.linshare.local`
