### ISSUE TITLE
Docker Version Error

### ISSUE THREAD

**Issue by fisherad** [linagora/linshare-docker#13]
root@fileserver:~/linshare-docker# docker-compose up -d
ERROR: Version in "./docker-compose.yml" is unsupported. You might be seeing this error because you're using the wrong Compose file version. Either specify a supported version (e.g "2.2" or "3.3") and place your service definitions under the `services` key, or omit the `version` key and place your service definitions at the root of the file to use version 1.
For more on the Compose file format versions, see https://docs.docker.com/compose/compose-file/

How do I resolve this.

**Comment by tolstoyfafa** [comment]
Hello,
Looks like you have an older docker version that doesn't support yet the docker-compose file version 3.7 used on LinShare.
required **docker** engine release : 18.06.0+
required **composer** release : Compose 1.21.0+
So try to install required versions.
Regards.

**Comment by fmartin-linagora** [comment]
Hi,
Without feedback, I am closing this issue.
