### ISSUE TITLE
Old version

### ISSUE THREAD

**Issue by Douaa57** [linagora/linshare-docker#16]
Hey,
I have a problem. When logging in as an administrator, several features are not accessible. 
![IMG-20220531-WA0026](https://user-images.githubusercontent.com/106668426/171390954-4f818e34-cee3-449c-ad48-be3d3af62c7d.jpeg)

**Comment by Douaa57** [comment]
Please if you have a solution to connect on the old interface, because when I click ok it leaves me on the new version

**Comment by Douaa57** [comment]
Even if i click on legacy admin portal, its redirects me to this link: http://admin.linshare.local/new/#/login

**Comment by fmartin-linagora** [comment]
Are you able to login into the new interface ?

**Comment by fmartin-linagora** [comment]
once logged in ui-admin (new), can you try to access to http://admin.linshare.local/  ?

Can you see the old interface ?

**Comment by fmartin-linagora** [comment]
Please use https://admin.linshare.local/

**Comment by fmartin-linagora** [comment]
Only use HTTPS.

You can access o the home page of all services using : https://home.linshare.local

**Comment by fmartin-linagora** [comment]
https://github.com/linagora/linshare-docker/ was updated.
