### ISSUE TITLE
request.linshare.local seems to be hardcoded

### ISSUE THREAD

**Issue by jocelynthode** [linagora/linshare-docker#2]
Hey,

the url request.linshare.local seems to be hardcoded in linshare. We didn't find a way to set it up other than in /etc/hosts

**Comment by fmartin-linagora** [comment]
Hi,
This URL could be updated in the administration interface of LinShare in Parameters/Functionalities/Upload request.

**Comment by fmartin-linagora** [comment]
Hi,
This URL could be updated in the administration interface of LinShare in Parameters/Functionalities/Upload request.
