### ISSUE TITLE
Docker-compose failed to bring up fronted with following error

### ISSUE THREAD

**Issue by denishpatel** [linagora/linshare-docker#3]
docker-compose up failed with error...

linshare_clamav | ClamAV update process started at Fri Jan 26 16:10:11 2018
linshare_clamav | WARNING: Your ClamAV installation is OUTDATED!
linshare_clamav | WARNING: Local version: 0.99.2 Recommended version: 0.99.3
linshare_clamav | DON'T PANIC! Read http://www.clamav.net/documents/upgrading-clamav
linshare_clamav | main.cvd is up to date (version: 58, sigs: 4566249, f-level: 60, builder: sigmgr)
linshare_clamav | LibClamAV Warning: **************************************************
linshare_clamav | LibClamAV Warning: ***  The virus database is older than 7 days!  ***
linshare_clamav | LibClamAV Warning: ***   Please update it as soon as possible.    ***
linshare_clamav | LibClamAV Warning: **************************************************
linshare_ui-admin | [Fri Jan 26 16:10:11.465983 2018] [mpm_event:notice] [pid 1:tid 140012694574976] AH00489: Apache/2.4.29 (Unix) configured -- resuming normal operations
linshare_ui-admin | [Fri Jan 26 16:10:11.468225 2018] [core:notice] [pid 1:tid 140012694574976] AH00094: Command line: 'httpd -D FOREGROUND'
linshare_smtp | info: OpenSMTPD 5.7.3p2 starting
linshare_smtp | info: startup
linshare_frontend | AH00534: httpd: Configuration error: No MPM loaded.

**Comment by leblanc-simon** [comment]
edit `conf/frontend.conf` and add `LoadModule mpm_prefork_module modules/mod_mpm_prefork.so`

**Comment by fmartin-linagora** [comment]
Or you can define frontend image : httpd:2.4.28. I'll fix it properly asap.
