### ISSUE TITLE
linshare.local dose not resolve

### ISSUE THREAD

**Issue by bogsi** [linagora/linshare-docker#5]
Hello,
i`ve successfully ran docker-compose up -d and edited my hosts file in the host VM which is based on vistualbox and OS is ubuntu 16.04.4 Server. But when i tryed to access by dns name id does not resolve. By ip is fine but this way users and admin panel are not accessible.

I`ve edited my routers config, also not resolving by dns name. Router is tp-link with os openwrt.

Any suggestions are welcome.
Will post configs if needed.

**Comment by bogsi** [comment]
Hello and thanks for your answer.
The issue is that in our case we have 40+ computers who need to use this platform. Should i add it to every computer in /etc/hosts file or there is more sophisticated solution?
Also we want to forward all linshare.local domains to our external domain. 
Is there any way to do it?
We have internal dns.
Thanks in advance.

**Comment by fmartin-linagora** [comment]
Hello updating you /etc/hosts is just for tests only. You must use real dns name for production and update linshare deploiement according to these dns names.

**Comment by fmartin-linagora** [comment]
Without any feedback, I'm closing this issue.
