### ISSUE TITLE
backend sed error

### ISSUE THREAD

**Issue by rob-01** [linagora/linshare-docker#6]
Hi all
How can I resolve this error in the backend container?

`sed: couldn't edit /etc/linshare/log4j.properties: not a regular file`

Thanks!

**Comment by fmartin-linagora** [comment]
Hi,
Maybe it is because /etc/linshare/log4j.properties is not a file in the pod, but a folder. It could happen when you try to mount a non-exiting file into the container using docker-compose.

**Comment by fmartin-linagora** [comment]
Without any feedback, I'm closing this issue.
