### ISSUE TITLE
Sharing URL to others. 

### ISSUE THREAD

**Issue by jianxinguocn** [linagora/linshare-docker#7]
There’s still a problem when I shared URL to others, which likes followings URL. Becuase URL has a # sign in the PATH, the browser only requests the first part of the URL to the server, which is ‘http://linshare-ui-user.local/'.  Could you please give me a suggestion? Thanks. 

http://linshare-ui-user.local/#/files/received?fileUuid=ab30ef2f-8185-4892-b00d-ff267d7d46ea

**Comment by jianxinguocn** [comment]
The configuration of domain in notification URL is set as linshare-ui-user.local, while it should be "files.linshare.local". 

linshare=# select * from functionality_string where functionality_id in (30, 57);
 functionality_id |          string_value          
------------------+--------------------------------
               30 | http://linshare-ui-user.local/
               57 | http://linshare-ui-user.local/

**Comment by fmartin-linagora** [comment]
Hi,
The part after the '#' is good. The server base URL (http://linshare-ui-user.local/ ) could be updated through the linshare-ui-admin interface,  section "Parameters/Functionalities", look for "Anonymous URL" for external sharing, and "Domain" for internal sharing.
Regards,

**Comment by fmartin-linagora** [comment]
Using the linshare-init container fixed this. I'm closing this issue.
