### ISSUE TITLE
Not data download for backend v2.2 via Dockerfile wget command

### ISSUE THREAD

**Issue by samson4649** [linagora/linshare-docker#8]
When building the image there is issues with the wget for the content server. 

https://nexus.linagora.com/service/local/artifact/maven/content?r=linshare-releases&g=org.linagora.linshare&a=linshare-core&v=2.2&p=war

The location is not accessible. Is there a location with directory listing available to show available versions?

**Comment by alamartiniere-Linagora** [comment]
Hello @samson4649 ,
the dockerfile has been updated to fix this issue. 
You can find all LinShare components listed by version [here](http://download.linshare.org/versions)
Regards,

Alvin
