### ISSUE TITLE
Customization for notification emails

### ISSUE THREAD

**Issue by alexcustos** [linagora/linshare-docker#9]
Hello, I have up and running LinShare based on this docker compose configuration.
```
Product version: 3.2.0
Core version: 2.2.2
```
I tried to customize notification emails layout and footer, so I created a new layout, footer, and configuration for my domain then modified them. Configuration looks consistent, but I continue receiving emails with the hardcoded layout. For example, here's the actual footer: https://github.com/linagora/linshare-core/blob/master/src/main/java/org/linagora/linshare/core/notifications/config/FooterCopyrightResource.java. I'm sure because it's not equal to the default footer for the LinShareRootDomain in the DB.

Could you please let me know what kind of problem this is?

**Comment by fred49** [comment]
Hi,
Sorry for the delay, I missed your issue. :s 
As I understood, you create a new mail layout, a new mail footer, a new mail configuration and then assigned to it the previous mail footer an mail layout. Finally, you updated your domain properties to use your new mail config. Correct me if I'm wrong please.

About this actual footer, it is related to the [license](http://download.linshare.org/LinShare-License_AfferoGPL-v3_en.pdf), you must keep this footer in every mail sent by LinShare.

I hope it answered to your questions.
